#!/bin/sh

rm *.aux
rm *.bbl
rm *.blg
rm *.log
rm *~
rm *.dvi


latex paper_ABSTRACT.tex 
latex paper_ABSTRACT.tex 
latex paper_ABSTRACT.tex 
latex paper_ABSTRACT.tex 
bibtex paper_ABSTRACT
latex paper_ABSTRACT.tex 
latex paper_ABSTRACT.tex 
latex paper_ABSTRACT.tex 
latex paper_ABSTRACT.tex 
dvips paper_ABSTRACT.dvi -o && ps2pdf paper_ABSTRACT.ps &&  rm *.ps

